feat(ci):Fixing publish.yml issues

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -51,7 +51,14 @@ jobs:
       # ============================================================
       - name: Import GPG private key
         run: |
-          echo "${{ env.GPG_PRIVATE_KEY }}" | gpg --batch --import || true
+          echo "${{ env.GPG_PRIVATE_KEY }}" | gpg --batch --import
+          CODE=$?
+          if [ "$CODE" != "0" ] && [ "$CODE" != "1" ]; then
+          echo "❌ GPG import failed with code $CODE"
+          exit $CODE
+          else
+          echo "✅ GPG import successful or already imported"
+          fi
           gpg --list-secret-keys --keyid-format=long | grep -i ${{ env.MAVEN_GPG_KEYNAME }}
 
       # ============================================================
